on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['4.0', '3.4', '3.3']
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ruby/setup-ruby@ba696adf55506673e48342a66e30f1f53cadeae0
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - run: gem install bundler:4.0.9
      - run: bundle install
      - run: bundle exec rubocop
    
  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['4.0', '3.4', '3.3']
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ruby/setup-ruby@ba696adf55506673e48342a66e30f1f53cadeae0
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - run: gem install bundler:4.0.9
      - run: bundle install
      - run: cat Gemfile.lock
      - run: bundle exec rspec
