on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.3', '3.2', '3.1', '3.0', '2.7']
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@360dc864d5da99d54fcb8e9148c14a84b90d3e88
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - run: gem install bundler:2.4.22
      - run: bundle install
      - run: bundle exec rubocop
    
  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.3', '3.2', '3.1', '3.0', '2.7']
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@360dc864d5da99d54fcb8e9148c14a84b90d3e88
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - run: gem install bundler:2.4.22
      - run: bundle install
      - run: cat Gemfile.lock
      - run: bundle exec rspec
